name: PR CI

on: [pull_request, pull_request_target]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - name: Install Node dependencies
        run: npm --prefer-offline --no-audit ci
      - name: Run tests
        run: npm test